# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: bbs-filter-dataset
#   namespace: default
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: bbs-filter-dataset
#     spec:
#       nodeSelector:
#         kubernetes.io/hostname: edge
#       containers:
#       - name: bbs-filter-dataset
#         image: mendonca/service-bbs-filter:0.1
#         command: ["/opt/bbs-filter"]
#         args: ["-u", "amqp://192.168.1.110:30000", "-f", "4.0", "-P", "dataset_"]
#         imagePullPolicy: Always
#         resources:
#           limits:
#             cpu: 500m
#             memory: 128Mi
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bbs-filter
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bbs-filter
    spec:
      nodeSelector:
        kubernetes.io/hostname: edge
      containers:
      - name: bbs-filter
        image: mendonca/service-bbs-filter:0.1
        command: ["/opt/bbs-filter"]
        args: ["-u", "amqp://192.168.1.110:30000", "-f", "4.0"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
